- name: variables
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false
  - name: DURATION
    prompt: Please enter duration time
  - name: TRAINEE
    prompt: please enter trainee name
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, trainee is {{ TRAINEE }}"
  