- name: variables
  hosts: local
  connection: local
  # vars:
  #   GREET: "PLAY"
  vars_files:
  - course-vars.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"


#1. command line or args
#2. task level
#3. prompt level
#4. play level
#5. inventory level
#6. Vars file level
#7. roles
