- name: DevOps course information
  hosts: local
  connection: local
  vars:
    course_name: "DevOps with AWS" #string
    duration: 120 #number
    topics: # list, [] means list
    - linux
    - ansible
    - shell
    - AWS
    live: true # boolean
    tools: # map,{} means map
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: "Hello I am learning {{ course_name}}, duration is {{ duration }}, topics are {{ topics }}. Is it live? - {{ live }}, tools used are {{ tools }}"


