- name: DevOps course info
  hosts: local
  connection: local
  vars:
    course_name: "DevOps with AWS" #string
    duration: 120 #number
    topics: # list, [] means list
    - linux
    - ansible
    - shell
    - AWS
    live: true # boolean
    tools: # map,{} means map
      ci: jenkins
      cloud: aws
      containerization: docker
    tasks:
    - name: print course info
      ansible.builtin.debug:
        msg: "Hello iam learning {{ course_name}}, duration is {{ duration }}, topics are {{ topics}}. Is it live? {{ live }}, tools used are {{ tool }}"


