- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
     msg: "Hello {{ person | default ('Krishna') }}"

  - name: convert string into list
    vars:
      fruits: "apple, banana,orange" #string
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"
  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10 hrs
        trainee: krishna
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10 hrs'}
      - {'key': 'trainee', 'value': 'krishna'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"

  - name: convert upper to lower
    vars:
      name: "Krishna CH"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower}}"

  - name: convert lower to upper
    vars:
      name: "krishna ch"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper}}"
    
  - name: print min and max
    vars:
      numbers: [1,25,50,75,100]
    ansible.builtin.debug:
      msg: "Min is {{ numbers | min}} and Max is {{ numbers | max }}"

  - name: check ipaddress is valid or not
    vars:
      ip: "254.088.224.02"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr}}"